apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "restart-controller.fullname" . }}
data:
  config.yaml: |
    services:
    {{- range $ns, $value := .Values.services }}
      {{- range $k, $v := $value }}
      - namespace: {{ $ns }}
        kind: {{ $v.kind }}
        name: {{ $v.name }}
      {{- end }}
    {{- end }}
