version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dep/go
      - dependabot
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dep/docker
      - dependabot
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dep/gh-actions
      - dependabot
